### ISSUE TITLE
"Teleporter" is too cute

### ISSUE THREAD

**Issue by jklynch** [tacaswell/mpl-qtthread#1]
The name "Teleporter" is not helpful for understanding what is going on here. A big chunk of documentation would go a long way to making up for the name. I am making a stink about this because I think this code should be a place to educate developers (such as myself) who don't understand, but have been bitten by, the problem this code solves.

**Comment by tacaswell** [comment]
Fair.  Other possible names:

- "bridge"
- "gateway"
- "forwarder"
- "trampoline"
- "proxy"
- "conduit"

**Comment by jklynch** [comment]
The problem I have with all those names is they are vague. What is being trampolined? I think it should be in the name.

**Comment by tacaswell** [comment]
The action of creating Qt objects is being moved from the calling thread to the event loop (which is presumed to be running on the main thread) is what is being teleported.
