### ISSUE TITLE
Would superqt's `ensure_main_thread` help here?

### ISSUE THREAD

**Issue by ianhi** [tacaswell/mpl-qtthread#2]
I don't fully understand things here so this is a bit of a drive by but would something like `superqt`s `ensure_main_thread` be helpful here? 
https://github.com/napari/superqt/blob/ba1ae92bccc282da040281751b71afcbe4c0e302/src/superqt/utils/_ensure_thread.py#L35

It really nicely solved a problem in napari-micromanager of errors when we tried to update the gui from not the main thread: https://github.com/tlambert03/napari-micromanager/pull/114

**Comment by tacaswell** [comment]
Oh, that would help! 

The guts of the implementation are at https://github.com/napari/superqt/blob/ba1ae92bccc282da040281751b71afcbe4c0e302/src/superqt/utils/_ensure_thread.py#L106-L125 and make use of a part of the Qt API I did not know existed until just now.

**Comment by ianhi** [comment]
Somewhat related: are you aware of qtpy? https://github.com/spyder-ide/qtpy#qtpy-abstraction-layer-for-pyqt5pyqt6pyside2pyside6

I know mpl has it's own qt compatibility layer, but maybe could use qtpy to simplify that?

**Comment by tacaswell** [comment]
We have talked about it (and I am roughly in favor).  But we have our own layer that we understand and it works for our needs.  It is not obvious that picking up a dependency (which will change / break under us 😈 ) is going to be less work in the long run.  Mix of sunk-cost fallacy and devil-you-know. 

Our compat layer is now also much better about detecting what is _already_ imported which I think blunts one of the biggest pro arguemnets for qtpy (if everyone uses qtpy -> harder for users to get into broken mixed states).

**Comment by tacaswell** [comment]
Re-reading the superqt implementation more carefully part of what I thought was Qt API was actually defined in that file too.  I think the core mechanism is the same (use signal/slots to move the work from the background thread to the main thread).  In the teleporter implementation we rely on having a singleton QObject that we use to push the work through (pro only one, con have to make it on the correct thread, was making custom signals per thing we wanted to push across).  In the superqt scheme there is a generic QObject that is inited with a callable + args + kwargs.  That object is then sent to the main thread and invoked.  Not sure of any cons, pros are it is simpler to explain and easier to use 🤷🏻 .
